### PR TITLE
Switch to Hugo

### LINKED ISSUE #11: improve contributors page
- read all contributors from all repos
- sort by contributions

The initial step is done in https://github.com/dev-sec/dev-sec.github.io/tree/hugo/tools/contributors

This script needs to be improved to use pagination. I also think we should use https://github.com/octokit/node-github instead of plain http calls

### LINKED ISSUE #12: imprint
the imprint is not up-to-date

### LINKED ISSUE #13: improve style for blog
The current blog https://bricklayer-mole-54424.netlify.com/blog/ needs to be improved in style

### LINKED ISSUE #14: improve style for docs
the previous docs http://dev-sec.io/docs/ was more optimised for documentation but had a different style than the rest of the page. We should harmonise that.  The current version is running here: https://bricklayer-mole-54424.netlify.com/docs/

### LINKED ISSUE #15: Show profile content
Place the inspec json for each profile in data directory and render it

### LINKED ISSUE #17: Roadmap for dev-sec web assets
At this point, we have three different repositories to main our web assets:

- https://github.com/dev-sec/dev-sec.github.io
- https://github.com/dev-sec/blog
- https://github.com/dev-sec/docs

This is very confusing to our users and does not encourage our community to update the content regularly. In addition, the project has extended its scope dramatically over the last year. We have a lot new profiles available that are not discoverable via the website. Those are only *visible* if your familiar with Github. Therefore, I am proposing the following steps:

Step 1: *Migrate*
- migrate all content as is to hugo in a single repository
- do not apply style changes to simplify the migration

Step 2: *update content*
- harmonize content
- page to discover all individual github projects
- leaderbaord to display top contributors similar to https://github.com/ejholmes/leaderboard

Step 3: *discoverability of profiles*
- turn home page in a profile-centric view similar to https://www.stigviewer.com/stig/windows_server_2016/
- align all hardening modules (ansible, chef, puppet) to a profile

### PR DESCRIPTION
**Pull request by chris-rock**
fixes #17
fixes #15
fixes #13
fixes #14
fixes #11
fixes #12

The current page is available https://bricklayer-mole-54424.netlify.com/

Since Github pages needs the master branch, we are going to have the hugo source in `src` branch and publish from there into the master branch

### CODE REVIEW

**Comment by artem-sidorenko** [comment]
> Since Github pages needs the master branch, we are going to have the hugo source in src branch and publish from there into the master branch

@chris-rock usually it works with `gh-pages` branch too, you can select that in the repo settings if branch exists. Maybe it would be a better approach if it works here?

**Comment by artem-sidorenko** [comment]
@chris-rock sign-off is missing, hihi :D

**Comment by chris-rock** [comment]
@artem-sidorenko Unfortunately gh-pages does not work for org pages, see https://gohugo.io/hosting-and-deployment/hosting-on-github/#deployment-via-docs-folder-on-master-branch and

image

**Review by atomic111 — APPROVED** [review]
@chris-rock fantastic work. big thanks!!!

**Comment by artem-sidorenko** [comment]
> @artem-sidorenko Unfortunately gh-pages does not work for org pages, see https://gohugo.io/hosting-and-deployment/hosting-on-github/#deployment-via-docs-folder-on-master-branch and

:-( 

@chris-rock Then another idea:
- two repos:
   - `dev-sec.github.io`
   - `homepage`
- new github bot user
- bot user has dedicated r/w access to `dev-sec.github.io`
- `homepage` has Travis CI job, which automatically publishes the content to `dev-sec.github.io` for master builds

I filed #19 with this idea. I'll be happy to implement this if you assist me with right management on the github side

**Comment by artem-sidorenko** [comment]
@chris-rock can you please close the issues mentioned in the PR body? They were not closed automatically and I have no rights to do so.

**Comment by chris-rock** [comment]
Thank you @artem-sidorenko Will do

**Pull request merged**
